Copy script to pull and setup repos in VM
coopdevs/katuma-provisioning-old pull request #6
Opened 2016-12-17 19:33 UTC by sauloperez

This copies the setup_repos.sh in the HOME as part of the provisioning, then you need to ssh into the machine and execute it.

It pulls both katuma and katuma-web repos and install their dependencies, including
setting up the database with its seed data.

This makes trivial setting up the environment and so easier for others to join the project. We can remove steps from the wiki! 🎉

2016-12-17 22:46 UTC, enricostano requested changes
I think it would be better to actually copy the script to the VM/container from Ansible, no need here to use more custom shell provisioning.

EDIT: Probably the best approach should be to create a new `development` role since this would be only needed for `development.yml`.

2016-12-17 22:51 UTC, sauloperez commented
Agree

2016-12-17 22:54 UTC, enricostano commented on setup_repos.sh
> +git clone git@github.com:coopdevs/katuma.git
The git clone is not needed for `LXC` containers.

2016-12-17 22:54 UTC, enricostano requested changes

2016-12-17 22:54 UTC, enricostano commented on setup_repos.sh
> +git clone git@github.com:coopdevs/katuma-web.git
ditto

2016-12-21 10:52 UTC, sauloperez commented
I'll reopen it doing it as @enricostano suggested

2016-12-21 10:52 UTC, closed without merging